language: node_js
node_js:
- "6"
cache:
  directories:
  - travis_phantomjs
  - node_modules
  - $HOME/.npm
before_install:
- openssl aes-256-cbc -K $encrypted_a2cfe6971b25_key -iv $encrypted_a2cfe6971b25_iv -in id_rsa.enc -out id_rsa -d
- export PHANTOMJS_VERSION=2.1.1
- export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
- if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs;
  mkdir -p $PWD/travis_phantomjs; fi
- if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
  -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi
- if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
  -C $PWD/travis_phantomjs; fi
- phantomjs --version
install: 
- npm install
script: 
- npm test
- npm run build
- npm run deploy
after_success:
branches:
  except:
  - gh-pages
env:
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="travis-ci.org"
  - GIT_EMAIL="travis@travis-ci.org"
  - SOURCE_DIR="."
  - DEPLOY_BRANCH="master"
